# ==================== BASE DE DATOS ====================
spring.datasource.url=jdbc:postgresql://dpg-d7v6n3b7uimc73efuk3g-a.virginia-postgres.render.com:5432/base_datos_ap6q?sslmode=require
spring.datasource.username=base_datos_ap6q_user
spring.datasource.password=ZjuMkrORXhM6GRM5UGrMSMGSSEChoSXI
spring.datasource.driver-class-name=org.postgresql.Driver

# ==================== JPA / HIBERNATE ====================sudo pacman -S bind
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ==================== THYMELEAF ====================
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

# ==================== MULTIPART ====================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB

# ==================== SESIONES ====================
server.servlet.session.timeout=60m

# ==================== APP ====================
spring.application.name=chamba
server.port=8080
app.nombre=Chamba